import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
import streamlit as st
from PIL import Image
import json as js
import yfinance as yf
import matplotlib.pyplot as plt
from scipy.stats import linregress